### PR TITLE
Zotero chapter

### PR DESCRIPTION
**Pull request by martaschoch**
Hi Andres, 
I've been working on the Zotero chapter, I tried to render it with the following code, but it is not working for me:
file <- "Referencing_using_Zotero.Rmd"
bookdown::render_book(file, "bookdown::gitbook",
                      preview = TRUE)
Am I forgetting something? 
Thanks!
Marta

### CODE REVIEW

**Comment by randrescastaneda** [comment]
Hi Marta,

Quick question. Which is the official file. The one with underscores “_” of the with spaces “ ”? I guess the former, but I just need to confirm.

Can I delete the other one or we need it for something?

Thank.
Best
----------------------
R.Andrés Castañeda

**Comment by martaschoch** [comment]
Thanks Andres, not sure why it kept both (Is this just because I renamed it?)-but yes the correct file is the: Referencing_using_Zotero.Rmd that I committed today. 
Marta

**Comment by randrescastaneda** [comment]
Thank you, Marta. 

It did not work for you because you needed to add the chapter title to the `rmd_files` files in the `_bookdown.yml` file. Like this.  Anyhow, no worries about it. I'll do it for you and let you know when the new version is ready. 

```yml
rmd_files: [
  "index.Rmd",
  "intro.Rmd",

  "Folder_structure.Rmd",
  "Collaboration_in_Git.Rmd",
  "DM_Group_data.Rmd",

  "prepare_data_for_update.Rmd",

  "Referencing_using_Zotero.Rmd",

  "Handover.Rmd",
  "references.Rmd",
]
```
Best,

**Comment by randrescastaneda** [comment]
Hi Marta, 

The book has been rebuild with your changes. PLease take a [look at it](https://povcalnet-team.github.io/Povcalnet_internal_guidelines/) and make modifications in a new branch as you see fit. 

Thank  you so much. Good job. 
Best,

**Pull request merged**
