### PR TITLE
Modify video links to make it run

### PR DESCRIPTION
**Pull request by martaschoch**
Modify video links in basic SmartGit process section to make it run

### CODE REVIEW

**Comment by randrescastaneda** [comment]
HI Marta,

Sorry, but your branch has conflict with the master branch.

Please, give me a call to whatsapp if you don’t know how to solve them. Otherwise, please solve them and then create I can check the pull request.

Thanks.
Best,
----------------------
R.Andrés Castañeda
Development Economics<https://www.worldbank.org/en/about/unit/unit-dec#2>, Data Group<https://data.worldbank.org/>/PovcalNet Team<http://iresearch.worldbank.org/PovcalNet/home.aspx>
The World Bank<https://www.worldbank.org/>|Washington, D.C.|+1 (202) 473-0108
MC 2-860<http://wbgmsmapq003.worldbank.org/bankquest/index2.php?id=MC2-860A&floorid=MC-02&auto=0>|WEBEX<https://worldbankgroup.webex.com/meet/pr1145171>|randrescastaneda.rbind.io<https://randrescastaneda.rbind.io/>

**Comment by martaschoch** [comment]
Hi Andres, I think I solved it (I just deleted the line that was there before I added the detailed sections), Can you please check?

**Comment by randrescastaneda** [comment]
Marta, 

Are you sure this is final? I got this error, 
`  Cannot find the file(s): "images/SG_stage.PNG"`
Best,

**Comment by martaschoch** [comment]
Hi Andres, I checked the chapter and all the images and videos are working (you can see the collaboration_in_git.html file that I committed yesterday). I have a couple of questions: is this pull request now ready to be merged in the master file? how come is it now showing a conflict anymore? 
Maybe we can discuss this during the next GitHub training :)
Marta

**Comment by randrescastaneda** [comment]
Hi Marta,

Thank you. I just merged your changes into the master branch and pushed everything. You can see that all your changes<https://povcalnet-team.github.io/Povcalnet_internal_guidelines/collaboration-in-git.html#getting-to-know-smartgit> are now in our official guidelines<https://povcalnet-team.github.io/Povcalnet_internal_guidelines/>.

Regarding your questions, yes the pull request was ready to be merged in master. Also, it does not have conflicts anymore because I reverted the commit that created the conflict. Everything is working now. Thank you!

Now, as you can see. There are some stylish things that are not working properly. For instance see the images below. Notice that references are not working fine. Also, note that the heading of the numerals is confused with the resto of the text. For example, numeral 6 reads “Create a new branch Branching is a crucial step…” The “Create a new branch” should be in a different style from the rest of the text.

[cid:image001.png@01D63E82.BD0636E0] [cid:image002.png@01D63E82.BD0636E0]


Please, check out the master branch and create a new branch from there. You don’t need to call it “Marta” or something like that. It is better if you give it a more meaning full name like “fix_style” or something like that.


Note: This fix is NOT urgent, so you can work on it in a couple of weeks.

Thank you so much.
Best,
----------------------
R.Andrés Castañeda

**Pull request merged**
